name: Gitea Actions Build
run-name: ${{ gitea.actor }} is Build out Gitea Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-dev
    steps:
      - name: Check out repository code
        uses: https://git.mingliqiye.com/Actions/checkout@v4

      - name: build
        run: |
          gradle
          gradle build
