name: Github Actions Build
run-name: ${{ github.actor }} is Build out Github Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-dev
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'


      - name: build
        run: |
          ./gradlew
          ./gradlew build
